# Generated by Django 5.1.6 on 2025-04-03 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_rentpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bill (e.g., Water Bill)', max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Total amount due for the bill', max_digits=10)),
                ('due_date', models.DateField(help_text='The due date for bill payment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', help_text='Payment status of the bill', max_length=10)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('garbage', 'Garbage'), ('other', 'Other')], help_text='Category of the bill', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the bill was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the bill was last updated')),
                ('property', models.ForeignKey(help_text='The property linked to the bill', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='properties.property')),
                ('tenant', models.ForeignKey(help_text='The tenant responsible for the bill', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
