# Generated by Django 5.1.6 on 2025-04-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        ('transaction', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='The transaction related to the bill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='transaction.transaction'),
        ),
    ]
